name: test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          node:
            - "10"
            - "12"
            - "14"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.node }}
      - name: Test
        run: |
          npm i
          npm test
